### ISSUE TITLE
webhook.cs missing

### ISSUE THREAD

**Issue by SaltyHampster** [TheC0mpany/NekoStealer#2]
sir, the file to place the webhook is missing.
![image](https://user-images.githubusercontent.com/49771787/127310953-c1d5bf5f-e242-4def-b7c0-bf08e7ed7d91.png)

**Comment by TheC0mpany** [comment]
add new existing file and select Config.cs that Webhook.cs you can delete

**Comment by SaltyHampster** [comment]
how do I do such

**Comment by TheC0mpany** [comment]
just google how add to project existing file
